version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - promnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - promnet

volumes:
   prometheus_data:
   grafana_data:

networks:
  promnet:
    driver: bridge